import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JButton;

public class App {
    public static void main(String[] args) throws Exception {
        JButton but;
        JButton but0;
        JButton but2;
        JButton but3;
        JButton but4;
        JButton but5;
        JButton but6;
        JButton but7;
        JButton but8;
        JButton but9;
        JButton butreiz;
        JButton butdal;
        JButton butplus;
        JButton butminus;
        JFrame frame = new JFrame("Autoplaca vadibas panelis profesionaliem");
        JTextField textfield;  
        butminus = new JButton("-");
        but = new JButton("1");
        but0 = new JButton("0");
        but2 = new JButton("2");
        but3 = new JButton("3");
        but4 = new JButton("4");
        but5 = new JButton("5");
        but6 = new JButton("6");
        but7 = new JButton("7");
        but8 = new JButton("8");
        but9 = new JButton("9");
        butreiz = new JButton("×");
        butdal = new JButton(":");
        butplus = new JButton("+");
        butminus.setBounds(50,50,50,50);
        but0.setBounds(50,50,50,50);
        but.setBounds(50,50,50,50);
        but2.setBounds(50,50,50,50);
        but3.setBounds(50,50,50,50);
        but4.setBounds(50,50,50,50);
        but5.setBounds(50,50,50,50);
        but6.setBounds(50,50,50,50);
        but7.setBounds(50,50,50,50);
        but8.setBounds(50,50,50,50);
        but9.setBounds(50,50,50,50);
        butreiz.setBounds(50,50,50,50);
        butdal.setBounds(50,50,50,50);
        butplus.setBounds(50,50,50,50);
        but0.setLocation(80,260);
        butminus.setLocation(200,260);
        but.setLocation(20,80);
        but2.setLocation(80,80);
        but3.setLocation(140,80);
        but4.setLocation(20,140);
        but5.setLocation(80,140);
        but6.setLocation(140,140);
        but7.setLocation(20,200);
        but8.setLocation(80,200);
        but9.setLocation(140,200);
        butreiz.setLocation(200,80);
        butdal.setLocation(200,140);
        butplus.setLocation(200,200);
        frame.add(but);
        frame.add(but0);
        frame.add(but2);
        frame.add(but3);
        frame.add(but4);
        frame.add(but5);
        frame.add(but6);
        frame.add(but7);
        frame.add(but8);
        frame.add(but9);
        frame.add(butreiz);
        frame.add(butdal);
        frame.add(butplus);
        frame.add(butminus);
     textfield = new JTextField("kalkulatora sadala");
     textfield.setBounds(50, 150, 200, 30);
     textfield.setLocation(20,20);
     frame.add(textfield);
    
     frame.setSize(800, 800);
     frame.setLayout(null);
     frame.setVisible(true);
    }
}
